# Generated by Django 5.2.9 on 2026-01-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_parent_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
