# Generated by Django 5.2.9 on 2026-01-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_visual_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='difficulty',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='hint',
            field=models.TextField(blank=True, help_text='Optional hint to aid recall', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Topic tags for organization'),
        ),
    ]
